version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./frontend:/app

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DB=endgame
      - DB_HOST=db
      - DB_PASS=example
      - DB_USER=john
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=endgame
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=example
    volumes:
      - db-data:/var/lib/postgresql/data

  db-replication-1:
    container_name: db_replica1
    image: postgres
    environment:
      - POSTGRES_DB=endgame
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=example
    volumes:
      - db-replication-1-data:/var/lib/postgresql/data
    depends_on:
      - db

  db-replication-2:
    container_name: db_replica2
    image: postgres
    environment:
      - POSTGRES_DB=endgame
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=example
    volumes:
      - db-replication-2-data:/var/lib/postgresql/data
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis
    depends_on:
      - frontend

volumes:
  db-data:
  db-replication-1-data:
  db-replication-2-data:
